### ISSUE TITLE
[Question] SBOM type

### ISSUE THREAD

**Issue by MasahiroDAIKOKU** [OpenChain-Project/Telco-WG#137]
## Question
In section 3.5, there is the following statement

_SBOMs conforming to the OpenChain Telco SBOM Guide MUST provide their SBOM Type as [defined by CISA](https://www.cisa.gov/sites/default/files/2023-04/sbom-types-document-508c.pdf) in the CreatorComment field._

How should SBOM Type be described in the CreatorComment field?

Because the CreatorComment field is free format text in the SPDX 2.x, it may be necessary to provide an example description.

**Comment by vargenau** [comment]
Hi Masahiro-san,

Yes, the CreatorComment field is free format text.

What we require is the presence of one of the keywords (Design, Source, Build, Analyzed, Deployed, Runtime) in this field.
This is what the validator checks. It checks the presence of these words, ignoring case (so you can have “Build”, “build”, “BUILD”, etc.)

You can also put in the field any additional information you want.

But I fully agree that we should be more explicit and add examples.

Best regards,

Marc-Etienne

--
Marc-Etienne Vargenau ***@***.******@***.***>
Nokia, 12, rue Jean-Bart, 91300 Massy, FRANCE
Mobile: +33 6 24 49 78 68<tel:+33624497868>
Senior Specialist Open Source
Planned absence: none


De : Masahiro DAIKOKU ***@***.***>
Date : vendredi, 6 décembre 2024 à 14:45
À : OpenChain-Project/Telco-WG ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [OpenChain-Project/Telco-WG] [Question] SBOM type (Issue #137)
Question

In section 3.5, there is the following statement

SBOMs conforming to the OpenChain Telco SBOM Guide MUST provide their SBOM Type as defined by CISA<https://www.cisa.gov/sites/default/files/2023-04/sbom-types-document-508c.pdf> in the CreatorComment field.

How should SBOM Type be described in the CreatorComment field?

Because the CreatorComment field is free format text in the SPDX 2.x, it may be necessary to provide an example description.

**Comment by MasahiroDAIKOKU** [comment]
Hi Marc-san,

Thank you very much for your kind reply.

Regarding the description of SBOM Type in section 3.5, since there was a question at the recent afternoon meeting, and since it is described in the third sentence of “Core > Vocabularies > SBOMType > Description” in the SPDX specification ver. 3.0.1, how about changing the description to the following to be aware of multiple SBOM types?

SBOMs … MUST provide their **SBOM Type** as defined by CISA in the CreatorComment field.
=> SBOMs … MUST provide their **SBOM Types** as defined by CISA in the CreatorComment field.
#There may be a more understandable expressions.

And, I confirmed that the open-chain-sbom-validation tool is already compatible with multiple SBOM Types, as it did not produce a nonconforming output when SBOM with multiple SBOM Types were inserted.
